// src/lib/utils.ts
// This file was generated by Shadcn UI during initialization.
// It exports the cn() utility function — the most important utility in the project.

import { clsx, type ClassValue } from "clsx";
// clsx is a function that accepts any combination of strings, objects, and arrays
// and produces a single className string.
// ClassValue is the TypeScript type for anything clsx accepts.

import { twMerge } from "tailwind-merge";
// twMerge merges Tailwind classes intelligently, resolving conflicts.

export function cn(...inputs: ClassValue[]) {
  // cn() accepts any number of arguments (...inputs means "rest parameters" —
  // collect all arguments into an array called inputs)

  return twMerge(clsx(inputs));
  // Step 1: clsx(inputs) → combines all the class values into one string,
  //         handling conditionals, arrays, objects, undefined values, etc.
  // Step 2: twMerge(...) → resolves any Tailwind conflicts in that string

  // Example:
  // cn("p-4", isLarge && "p-8", undefined, "text-white")
  // → clsx produces: "p-4 p-8 text-white"  (if isLarge is true)
  // → twMerge resolves: "p-8 text-white"   (p-4 conflict removed)
}